// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package genproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RivendellClient is the client API for Rivendell service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RivendellClient interface {
	GetProducts(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetProductsResponse, error)
}

type rivendellClient struct {
	cc grpc.ClientConnInterface
}

func NewRivendellClient(cc grpc.ClientConnInterface) RivendellClient {
	return &rivendellClient{cc}
}

func (c *rivendellClient) GetProducts(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetProductsResponse, error) {
	out := new(GetProductsResponse)
	err := c.cc.Invoke(ctx, "/rivendell.Rivendell/GetProducts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RivendellServer is the server API for Rivendell service.
// All implementations must embed UnimplementedRivendellServer
// for forward compatibility
type RivendellServer interface {
	GetProducts(context.Context, *Empty) (*GetProductsResponse, error)
	mustEmbedUnimplementedRivendellServer()
}

// UnimplementedRivendellServer must be embedded to have forward compatible implementations.
type UnimplementedRivendellServer struct {
}

func (UnimplementedRivendellServer) GetProducts(context.Context, *Empty) (*GetProductsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProducts not implemented")
}
func (UnimplementedRivendellServer) mustEmbedUnimplementedRivendellServer() {}

// UnsafeRivendellServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RivendellServer will
// result in compilation errors.
type UnsafeRivendellServer interface {
	mustEmbedUnimplementedRivendellServer()
}

func RegisterRivendellServer(s grpc.ServiceRegistrar, srv RivendellServer) {
	s.RegisterService(&Rivendell_ServiceDesc, srv)
}

func _Rivendell_GetProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RivendellServer).GetProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rivendell.Rivendell/GetProducts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RivendellServer).GetProducts(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Rivendell_ServiceDesc is the grpc.ServiceDesc for Rivendell service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Rivendell_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rivendell.Rivendell",
	HandlerType: (*RivendellServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProducts",
			Handler:    _Rivendell_GetProducts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "contract.proto",
}
